name: ci/cd with bad practise
# запуск на всех ветках
on:
  push:
    branches:
      - '*'
# все шаги в одной джобе, нет деления на билд тест деплой
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Плохая практика 3: Установка зависимостей без создания виртуального окружения
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Установка в глобальное окружение может вызвать конфликты

      # Плохая практика 4: пропуск тестов
      - name: Skip tests
        run: echo "Skipping tests"

      # Плохая практика 5: Не обрабатывать ошибки и не выводить их в лог
      - name: Build and deploy
        run: |
          echo "Building the project..."  # Отсутствие проверки успешности предыдущих шагов
          

